# File: .gitlab-ci.yml
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  GCR_REPO_STAGING: gcr.io/$GCP_PROJECT_ID_STAGING/linkedin-fetcher-api
  GCR_REPO_PRODUCTION: gcr.io/$GCP_PROJECT_ID_PRODUCTION/linkedin-fetcher-api

stages:
  - format-check
  - build
  - deploy_staging
  - deploy_production

format-check:
  stage: format-check
  script:
    - apk add --update python3 py3-pip
    - pip3 install --upgrade pip
    - pip install black
    - black --check .

build:
  stage: build
  image: google/cloud-sdk
  script:
    - mkdir -p credentials
    - echo $GCP_SERVICE_ACCOUNT_KEY_STAGING > credentials/gcloud-service-account-key.json
    - gcloud auth activate-service-account --key-file credentials/gcloud-service-account-key.json
    - gcloud auth configure-docker --quiet
    - docker build -t $GCR_REPO_STAGING:$CI_COMMIT_SHA .
    - docker push $GCR_REPO_STAGING:$CI_COMMIT_SHA

deploy_staging:
  stage: deploy_staging
  image: google/cloud-sdk
  environment:
    name: staging
  script:
    - mkdir -p credentials
    - echo $GCP_SERVICE_ACCOUNT_KEY_STAGING > credentials/gcloud-service-account-key.json
    - gcloud auth activate-service-account --key-file credentials/gcloud-service-account-key.json
    - gcloud config set project $GCP_PROJECT_ID_STAGING
    - export NEW_ENV_VARS=$(env | grep '^APP_' | sed 's/^APP_//' | tr '\n' ',' | sed 's/,$//')
    - gcloud run deploy linkedin-fetcher-api-staging --image $GCR_REPO_STAGING:$CI_COMMIT_SHA --region europe-west1 --platform managed --allow-unauthenticated --update-env-vars=$NEW_ENV_VARS --quiet


deploy_production:
  stage: deploy_production
  image: google/cloud-sdk
  when: manual
  needs:
    - deploy_staging
  environment:
    name: production
  script:
    - mkdir -p credentials
    - echo $GCP_SERVICE_ACCOUNT_KEY_STAGING > credentials/gcloud-service-account-key.json
    - gcloud auth activate-service-account --key-file credentials/gcloud-service-account-key.json
    - gcloud auth configure-docker --quiet
    - docker pull $GCR_REPO_STAGING:$CI_COMMIT_SHA
    - docker tag $GCR_REPO_STAGING:$CI_COMMIT_SHA $GCR_REPO_PRODUCTION:$CI_COMMIT_SHA
    - echo $GCP_SERVICE_ACCOUNT_KEY_PRODUCTION > credentials/gcloud-service-account-key.json
    - gcloud auth activate-service-account --key-file credentials/gcloud-service-account-key.json
    - docker push $GCR_REPO_PRODUCTION:$CI_COMMIT_SHA
    - gcloud config set project $GCP_PROJECT_ID_PRODUCTION

    - export NEW_ENV_VARS=$(env | grep '^APP_' | sed 's/^APP_//' | tr '\n' ',' | sed 's/,$//')
    # Depoloy
    - gcloud run deploy linkedin-fetcher-api-production --image $GCR_REPO_PRODUCTION:$CI_COMMIT_SHA --region europe-west1 --platform managed --allow-unauthenticated --update-env-vars=$NEW_ENV_VARS --quiet